export const GET_GROCERIES_REQUEST="GET_GROCERIES_REQUEST"
export const GET_GROCERIES_SUCCESS="GET_GROCERIES_SUCCESS"
export const GET_GROCERIES_FAILURE="GET_GROCERIES_FAILURE"

export const GET_PREMIUMFRUUIT_REQUEST="GET_PREMIUMFRUUIT_REQUEST"
export const GET_PREMIUMFRUUIT_SUCCESS="GET_PREMIUMFRUUIT_SUCCESS"
export const GET_PREMIUMFRUUIT_FAILURE="GET_PREMIUMFRUUIT_FAILURE"

export const GET_HOMEKITCHEN_REQUEST="GET_HOMEKITCHEN_REQUEST"
export const GET_HOMEKITCHEN_SUCCESS="GET_HOMEKITCHEN_SUCCESS"
export const GET_HOMEKITCHEN_FAILURE="GET_HOMEKITCHEN_FAILURE"

export const GET_ELECTRONICS_REQUEST="GET_ELECTRONICS_REQUEST"
export const GET_ELECTRONICS_SUCCESS="GET_ELECTRONICS_SUCCESS"
export const GET_ELECTRONICS_FAILURE="GET_ELECTRONICS_FAILURE"

export const GET_FASHION_REQUEST="GET_FASHION_REQUEST"
export const GET_FASHION_SUCCESS="GET_FASHION_SUCCESS"
export const GET_FASHION_FAILURE="GET_FASHION_FAILURE"

export const GET_BEAUTY_REQUEST="GET_BEAUTY_REQUEST"
export const GET_BEAUTY_SUCCESS="GET_BEAUTY_SUCCESS"
export const GET_BEAUTY_FAILURE="GET_BEAUTY_FAILURE"

export const GET_JEWELLERY_REQUEST="GET_JEWELLERY_REQUEST"
export const GET_JEWELLERY_SUCCESS="GET_JEWELLERY_SUCCESS"
export const GET_JEWELLERY_FAILURE="GET_JEWELLERY_FAILURE"